#version: "3"

services:
  certbot :
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    # depends_on:
    #   - conzept
  conzept:
    container_name: conzept
    # env_file:
    #   - .env
    build:
      context: .
    volumes:
      - sslvolume:/etc/ssl
      - ./data/certbot/conf:/etc/letsencrypt/
      - ./data/certbot/www:/var/www/certbot

      # only use these mappings during local development (never commit!):
      # FIXME: not yet producing a working build.
      #- app:/var/www/html/app
      #- /var/www/html/app/explore2/node_modules

    ports:
      - 80:80
      - 443:443
    restart: on-failure

volumes:
  sslvolume:
  app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./app
    #external: true
